name: SAST Scan

on:
  push:

jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit
        run: bandit -r . -f txt -o sast_report.txt || true
      - name: Upload SAST report
        uses: actions/upload-artifact@v4
        with:
          name: sast-report
          path: sast_report.txt
